              name: Deploy to Neocities
              uses: bcomnes/deploy-to-neocities@v2.0.2
            
  with:
    # Neocities API token for site to deploy to
    api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
    # Local folder to deploy to neocities
    dist_dir: ./neocitiesdeploy
    # Delete orphaned files on neocities that don't exist in distDir
    cleanup: true
    # A glob string that prevents matched files from ever being deleted.
    protected_files: # optional
          
